# Generated by Django 5.2.7 on 2025-10-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名9a881e917254', max_length=30, unique=True),
        ),
    ]
