# Generated by Django 5.2.7 on 2025-10-29 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名6b42c6cb05b6', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'このフィールドは必須です。', 'unique': 'そのユーザー名は既に存在します。'}, help_text='ユーザー名は必須です。150文字以内。英字、数字、@/./+/-/_ のみ使用可能です。', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='有効なユーザー名を入力してください。この値には英字、数字、@/./+/-/_ 文字のみを含めることができます。', regex='^[\\w.@+-]+$')]),
        ),
    ]
