# Generated by Django 5.2.7 on 2025-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_superuser_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名5345073ea064', max_length=30, unique=True),
        ),
    ]
