# Generated by Django 5.2.7 on 2025-11-02 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー 一覧'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名3a1dad52af24', max_length=30, unique=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'このフィールドは必須です。', 'unique': 'そのユーザー名は既に存在します。'}, help_text='ユーザー名は必須です。150文字以内。英字、数字、@/./+/-/_ のみ使用可能です。', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='有効なユーザー名を入力してください。この値には英字、数字、@/./+/-/_ 文字のみを含めることができます。', regex='^[\\w.@+-]+$')], verbose_name='ユーザー名'),
        ),
    ]
