# Generated by Django 5.2.7 on 2025-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名594ed729c8de', max_length=30, unique=True, verbose_name='ニックネーム'),
        ),
    ]
