# Generated by Django 5.2.7 on 2025-11-02 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='スタンプ名は必須です。固有の名前を指定してください。', max_length=100, unique=True, verbose_name='スタンプ名')),
                ('score', models.IntegerField(default=0, help_text='スタンプのスコアを整数で指定してください。', verbose_name='スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'スタンプ',
                'verbose_name_plural': 'スタンプ一覧',
            },
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, help_text='気持ちに関するコメントを入力してください。', max_length=500, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feelings', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feelings', to='stamps.stamp', verbose_name='スタンプ')),
            ],
            options={
                'verbose_name': '気持ち',
                'verbose_name_plural': '気持ち一覧',
            },
        ),
    ]
